# Generated by Django 4.0.4 on 2022-05-02 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doors', models.PositiveSmallIntegerField()),
                ('seats', models.PositiveSmallIntegerField()),
                ('ac', models.BooleanField()),
                ('gearbox', models.CharField(choices=[('AMT', 'Automated Manual Transmission'), ('CVT', 'Continuous Variable Transmission'), ('DCT', 'Dual Clutch Transmission'), ('TC', 'Torque Converters'), ('IMT', 'Intelligent Manual Transmission')], max_length=3)),
                ('fuel', models.CharField(choices=[('G', 'Gasoline'), ('D', 'Diesel'), ('BD', 'Bio Diesel'), ('E', 'Ethanol')], max_length=2)),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('carModelPrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SUV', 'Sports Utility Vehicle'), ('H', 'Hatchback'), ('CO', 'Crossover'), ('CI', 'Convertible'), ('S', 'Sedan'), ('SC', 'Sports Car'), ('CP', 'Coupe'), ('M', 'Minivan'), ('SW', 'Station Wagon'), ('PT', 'Pickup Truck')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=187)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'Admin'), ('R', 'Reservation'), ('C', 'Car')], max_length=1)),
                ('nic', models.CharField(max_length=8)),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('birthday', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('picture', models.CharField(max_length=260)),
                ('active', models.BooleanField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('price', models.FloatField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.car')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
            ],
        ),
    ]
