# Generated by Django 4.0.6 on 2022-07-17 08:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=2000)),
                ('doors', models.PositiveSmallIntegerField()),
                ('seats', models.PositiveSmallIntegerField()),
                ('ac', models.BooleanField()),
                ('gearbox', models.CharField(choices=[('AMT', 'Automated Manual Transmission'), ('CVT', 'Continuous Variable Transmission'), ('DCT', 'Dual Clutch Transmission'), ('TC', 'Torque Converters'), ('IMT', 'Intelligent Manual Transmission')], max_length=3)),
                ('fuel', models.CharField(choices=[('G', 'Gasoline'), ('D', 'Diesel'), ('BD', 'Bio Diesel'), ('E', 'Ethanol')], max_length=2)),
                ('year', models.PositiveSmallIntegerField()),
                ('picture', models.ImageField(default='cars/default.png', upload_to='cars/')),
            ],
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('car_model_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SUV', 'Sports Utility Vehicle'), ('H', 'Hatchback'), ('CO', 'Crossover'), ('CI', 'Convertible'), ('S', 'Sedan'), ('SC', 'Sports Car'), ('CP', 'Coupe'), ('M', 'Minivan'), ('SW', 'Station Wagon'), ('PT', 'Pickup Truck')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('status_reason', models.CharField(max_length=500)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField()),
                ('paid', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.car')),
            ],
        ),
    ]
