# Generated by Django 4.0.6 on 2022-07-17 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0012_alter_city_id_alter_country_id_alter_region_id_and_more'),
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employee.reservation'),
        ),
        migrations.AddField(
            model_name='employeelog',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car_who_got', to='employee.car'),
        ),
        migrations.AddField(
            model_name='employeelog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_who_got', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeelog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_who_did', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeelog',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.reservation'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.carbrand'),
        ),
        migrations.AddField(
            model_name='car',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.agency'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.carmodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.cartype'),
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities_light.city'),
        ),
    ]
