# Generated by Django 4.0.4 on 2022-05-06 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_light', '0011_alter_city_country_alter_city_id_alter_city_region_and_more'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeelog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='carBrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.carbrand'),
        ),
        migrations.AddField(
            model_name='car',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.agency'),
        ),
        migrations.AddField(
            model_name='car',
            name='carModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.carmodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='carType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.cartype'),
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities_light.city'),
        ),
    ]
