# Generated by Django 4.0.4 on 2022-05-02 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user'),
        ),
        migrations.AddField(
            model_name='employeelog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.agency'),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.city'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='carBrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.carbrand'),
        ),
        migrations.AddField(
            model_name='car',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.agency'),
        ),
        migrations.AddField(
            model_name='car',
            name='carModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.carmodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='carType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.cartype'),
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.city'),
        ),
    ]
