# Generated by Django 4.0.4 on 2022-05-09 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='inactive_reason',
            new_name='status_reason',
        ),
        migrations.AlterField(
            model_name='employeelog',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car_who_got', to='employee.car'),
        ),
    ]
