# Generated by Django 4.0.4 on 2022-05-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='inactive_reason',
            new_name='status_reason',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('C', 'Client'), ('CM', 'ClientManager'), ('RM', 'ReservationManager'), ('VM', 'VehicleManager')], max_length=2, unique=True),
        ),
    ]
