# Generated by Django 4.0.4 on 2022-05-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='status_reason',
            new_name='inactive_reason',
        ),
    ]
